# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: host
    main: ./cmd/host/main.go
    binary: host-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: node
    main: ./cmd/node/main.go
    binary: node-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - id: host
    package_name: host-agent
    builds:
      - host
    vendor: Kubescape
    homepage: https://kubescape.io/
    maintainer: matthias.bertschy@gmail.com
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: configuration/node-hash-sensor
        dst: /etc/host-agent
      - src: scripts/host-agent.service
        dst: /usr/lib/systemd/system/host-agent.service
    scripts:
      postinstall: "scripts/postinstall.sh"
      postremove: "scripts/postremove.sh"

docker_manifests:
  - name_template: "quay.io/kubescape/node-agent:{{ .Tag }}"
    image_templates:
      - "quay.io/kubescape/node-agent:{{ .Tag }}-amd64"
      - "quay.io/kubescape/node-agent:{{ .Tag }}-arm64"
dockers:
  - image_templates:
      - "quay.io/kubescape/node-agent:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg"
      - "image_version={{ .Tag }}"
    ids:
      - node
    dockerfile: build/Dockerfile
    extra_files:
      - configuration/ig-config.yaml
  - image_templates:
      - "quay.io/kubescape/node-agent:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg"
      - "image_version={{ .Tag }}"
    goarch: arm64
    ids:
      - node
    dockerfile: build/Dockerfile
    extra_files:
      - configuration/ig-config.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
