apiVersion: kubescape.io/v1
kind: RuntimeRuleAlertBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kubescape
    meta.helm.sh/release-namespace: kubescape
  creationTimestamp: "2024-11-26T11:07:08Z"
  generation: 1
  labels:
    app: node-agent
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/version: 1.23.2
    helm.sh/chart: kubescape-operator-1.23.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: all-rules-all-pods
  resourceVersion: "516"
  uid: 78bc578c-6374-4641-adc3-a5f067d5a748
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kubescape
      - kube-system
      - kube-public
      - kube-node-lease
      - kubeconfig
      - gmp-system
      - gmp-public
  rules:
  - ruleName: Unexpected process launched
  - parameters:
      ignoreMounts: true
      ignorePrefixes:
      - /proc
      - /run/secrets/kubernetes.io/serviceaccount
      - /var/run/secrets/kubernetes.io/serviceaccount
      - /tmp
    ruleName: Unexpected file access
  - ruleName: Unexpected system call
  - ruleName: Unexpected capability used
  - ruleName: Unexpected domain request
  - ruleName: Unexpected Service Account Token Access
  - ruleName: Kubernetes Client Executed
  - ruleName: Exec from malicious source
  - ruleName: Kernel Module Load
  - ruleName: Exec Binary Not In Base Image
  - ruleName: Malicious SSH Connection
  - ruleName: Fileless Execution
  - ruleName: Exec from mount
  - ruleName: Crypto Mining Related Port Communication
  - ruleName: Crypto Mining Domain Communication
  - ruleName: Read Environment Variables from procfs
  - ruleName: eBPF Program Load
  - ruleName: Symlink Created Over Sensitive File
  - ruleName: Unexpected Sensitive File Access
  - ruleName: Hardlink Created Over Sensitive File
  - ruleName: Exec to pod
  - ruleName: Port forward
  - ruleName: Unexpected Egress Network Traffic
  - ruleName: Malicious Ptrace Usage
  - ruleName: Crypto Miner detected
