// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSBOMRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ImageId             string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageTag            string                 `protobuf:"bytes,2,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	LayerPaths          []string               `protobuf:"bytes,3,rep,name=layer_paths,json=layerPaths,proto3" json:"layer_paths,omitempty"`
	ImageStatus         []byte                 `protobuf:"bytes,4,opt,name=image_status,json=imageStatus,proto3" json:"image_status,omitempty"`
	MaxImageSize        int64                  `protobuf:"varint,5,opt,name=max_image_size,json=maxImageSize,proto3" json:"max_image_size,omitempty"`
	MaxSbomSize         int32                  `protobuf:"varint,6,opt,name=max_sbom_size,json=maxSbomSize,proto3" json:"max_sbom_size,omitempty"`
	EnableEmbeddedSboms bool                   `protobuf:"varint,7,opt,name=enable_embedded_sboms,json=enableEmbeddedSboms,proto3" json:"enable_embedded_sboms,omitempty"`
	TimeoutSeconds      int64                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateSBOMRequest) Reset() {
	*x = CreateSBOMRequest{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSBOMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSBOMRequest) ProtoMessage() {}

func (x *CreateSBOMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSBOMRequest.ProtoReflect.Descriptor instead.
func (*CreateSBOMRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSBOMRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateSBOMRequest) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *CreateSBOMRequest) GetLayerPaths() []string {
	if x != nil {
		return x.LayerPaths
	}
	return nil
}

func (x *CreateSBOMRequest) GetImageStatus() []byte {
	if x != nil {
		return x.ImageStatus
	}
	return nil
}

func (x *CreateSBOMRequest) GetMaxImageSize() int64 {
	if x != nil {
		return x.MaxImageSize
	}
	return 0
}

func (x *CreateSBOMRequest) GetMaxSbomSize() int32 {
	if x != nil {
		return x.MaxSbomSize
	}
	return 0
}

func (x *CreateSBOMRequest) GetEnableEmbeddedSboms() bool {
	if x != nil {
		return x.EnableEmbeddedSboms
	}
	return false
}

func (x *CreateSBOMRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CreateSBOMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SbomDocument  []byte                 `protobuf:"bytes,1,opt,name=sbom_document,json=sbomDocument,proto3" json:"sbom_document,omitempty"`
	SbomSize      int64                  `protobuf:"varint,2,opt,name=sbom_size,json=sbomSize,proto3" json:"sbom_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSBOMResponse) Reset() {
	*x = CreateSBOMResponse{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSBOMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSBOMResponse) ProtoMessage() {}

func (x *CreateSBOMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSBOMResponse.ProtoReflect.Descriptor instead.
func (*CreateSBOMResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSBOMResponse) GetSbomDocument() []byte {
	if x != nil {
		return x.SbomDocument
	}
	return nil
}

func (x *CreateSBOMResponse) GetSbomSize() int64 {
	if x != nil {
		return x.SbomSize
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\x0esbomscanner.v1\"\xb6\x02\n" +
	"\x11CreateSBOMRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1b\n" +
	"\timage_tag\x18\x02 \x01(\tR\bimageTag\x12\x1f\n" +
	"\vlayer_paths\x18\x03 \x03(\tR\n" +
	"layerPaths\x12!\n" +
	"\fimage_status\x18\x04 \x01(\fR\vimageStatus\x12$\n" +
	"\x0emax_image_size\x18\x05 \x01(\x03R\fmaxImageSize\x12\"\n" +
	"\rmax_sbom_size\x18\x06 \x01(\x05R\vmaxSbomSize\x122\n" +
	"\x15enable_embedded_sboms\x18\a \x01(\bR\x13enableEmbeddedSboms\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x03R\x0etimeoutSeconds\"V\n" +
	"\x12CreateSBOMResponse\x12#\n" +
	"\rsbom_document\x18\x01 \x01(\fR\fsbomDocument\x12\x1b\n" +
	"\tsbom_size\x18\x02 \x01(\x03R\bsbomSize\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready2\xab\x01\n" +
	"\vSBOMScanner\x12S\n" +
	"\n" +
	"CreateSBOM\x12!.sbomscanner.v1.CreateSBOMRequest\x1a\".sbomscanner.v1.CreateSBOMResponse\x12G\n" +
	"\x06Health\x12\x1d.sbomscanner.v1.HealthRequest\x1a\x1e.sbomscanner.v1.HealthResponseB:Z8github.com/kubescape/node-agent/pkg/sbomscanner/v1/protob\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scanner_proto_goTypes = []any{
	(*CreateSBOMRequest)(nil),  // 0: sbomscanner.v1.CreateSBOMRequest
	(*CreateSBOMResponse)(nil), // 1: sbomscanner.v1.CreateSBOMResponse
	(*HealthRequest)(nil),      // 2: sbomscanner.v1.HealthRequest
	(*HealthResponse)(nil),     // 3: sbomscanner.v1.HealthResponse
}
var file_scanner_proto_depIdxs = []int32{
	0, // 0: sbomscanner.v1.SBOMScanner.CreateSBOM:input_type -> sbomscanner.v1.CreateSBOMRequest
	2, // 1: sbomscanner.v1.SBOMScanner.Health:input_type -> sbomscanner.v1.HealthRequest
	1, // 2: sbomscanner.v1.SBOMScanner.CreateSBOM:output_type -> sbomscanner.v1.CreateSBOMResponse
	3, // 3: sbomscanner.v1.SBOMScanner.Health:output_type -> sbomscanner.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
