apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: load-simulator
spec:
  selector:
    matchLabels:
      app: load-simulator
  template:
    metadata:
      labels:
        app: load-simulator
    spec:
      containers:
        - name: load-simulator
          image: quay.io/armosec/load-simulator:v2@sha256:43fd31ec3f86d318629e437bdf8c2859176f6131078798fcf322f93d29ad051b
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: config
