# Use the official PHP image
FROM php:7.4-apache

# Install ping
RUN apt-get update && \
    apt-get install -y iputils-ping wget curl python3 python3-pip && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m pip install boto3 && \
    python3 -c "import boto3; import json; import time; s3 = boto3.client('s3')"

# Copy the PHP script and index.html files into the container
COPY ping.php /var/www/html/
COPY index.html /var/www/html/

# Expose port 80 for Apache
EXPOSE 80

# Start Apache in the foreground
CMD ["sh", "-c", "docker-php-entrypoint apache2-foreground"]

