name: build
on:
  workflow_dispatch:

jobs:
  reset-run-number:
    runs-on: ubuntu-latest
    name: reset github.run_number
    outputs:
      run-number: ${{ steps.get-build.outputs.build-number }}
    steps:
    - name: Get build number
      id: get-build
      uses: mlilback/build-number@v1
      with:
        base: -144
        run-id: ${{ github.run_number }}

  pr-merged:
    needs: reset-run-number
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-merged.yaml@main
    with:
      IMAGE_NAME: quay.io/${{ github.repository_owner }}/node-agent
      IMAGE_TAG: v0.2.${{ needs.reset-run-number.outputs.run-number }}
      COMPONENT_NAME: nodeAgent
      CGO_ENABLED: 0
      GO111MODULE: "on"
      BUILD_PLATFORM: linux/amd64,linux/arm64
      GO_VERSION: "1.23"
      REQUIRED_TESTS: ''
      FORCE: true
      COSIGN: true
      HELM_E2E_TEST: true
    secrets: inherit
