name: pull_request_created
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '*.md'
      - '*.yaml'
      - '.github/workflows/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pr-created:
    permissions:
      contents: read
      actions: read
      security-events: write  # Pass CodeQL permissions through nested workflows.
    uses: ./.github/workflows/incluster-comp-pr-created.yaml
    with:
      GO_VERSION: "1.27"
      CGO_ENABLED: 0
    secrets: inherit
